# Generated by Django 4.1.4 on 2023-01-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.CharField(blank=True, max_length=110, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='عکس پروفایل'),
        ),
    ]
