# Generated by Django 4.1.4 on 2023-02-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_twitt_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitt',
            options={'ordering': ['-created']},
        ),
    ]
